checkstyle/regression-tool

- .gitignore
- .travis.yml
- LICENSE
- config/checkstyle.properties
- config/import-control.xml
- config/suppressions.xml
- pom.xml
- src/main/java/com/github/checkstyle/regression/Main.java
- src/main/java/com/github/checkstyle/regression/package-info.java
Taken from https://github.com/checkstyle/regression-tool/pull/1#issuecomment-306205248
> Pull #7: configs, travis, license and other basic settings

- pom.xml
Issue #8
Added code coverage verification.
Main and project is set to 0 for now. Coverage should increase with every new code to main, I hope.
It doesn't have to be 100%.
> Issue #8: added cobertura code coverage

- config/findbugs-exclude.xml
- pom.xml
Issue #8 
Added find bugs validation.
Accidentally added find bugs property last commit instead of pmd. This commit will fix that mistake by adding pmd's.
> Issue #8: added find bugs validation

- config/sevntu_suppressions.xml
- config/suppressions.xml
- src/test/java/com/github/checkstyle/regression/internal/CommitValidationTest.java
Issue #8 
Added commit validation test from checkstyle.
> Issue #8: added commit validation test

- src/test/java/com/github/checkstyle/regression/internal/CommitValidationTest.java
My eclipse setup was a little funky at the time.
> minor: fixed invalid path in commit validation test

- config/import-control.xml
- src/main/java/com/github/checkstyle/regression/data/GitChange.java
- src/main/java/com/github/checkstyle/regression/data/package-info.java
- src/main/java/com/github/checkstyle/regression/git/DiffParser.java
- src/test/java/com/github/checkstyle/regression/git/DiffParserTest.java
> Issue #24: GitChange should be moved to data package

- src/main/java/com/github/checkstyle/regression/git/DiffParser.java
> Issue #23: DiffParser.parse should close/free resources on exceptions

- appveyor.yml
> Issue #34: added appveyor CI

- config/findbugs-exclude.xml
- config/import-control.xml
- config/pmd.xml
- config/suppressions.xml
- pom.xml
- src/main/java/com/github/checkstyle/regression/data/ModuleExtractInfo.java
- src/main/java/com/github/checkstyle/regression/data/ModuleInfo.java
Taken from #33 . This is blocked by #38
> Issue #19: Add data object

- src/main/java/com/github/checkstyle/regression/git/DiffParser.java
- src/test/java/com/github/checkstyle/regression/git/DiffParserTest.java
- src/test/java/com/github/checkstyle/regression/internal/GitUtils.java
> Issue #25: handle the tracking of deleted changes

- src/main/java/com/github/checkstyle/regression/data/GitChange.java
- src/main/java/com/github/checkstyle/regression/git/DiffParser.java
- src/main/java/com/github/checkstyle/regression/module/ModuleUtils.java
- src/test/java/com/github/checkstyle/regression/git/DiffParserTest.java
- src/test/java/com/github/checkstyle/regression/internal/GitUtils.java
- src/test/java/com/github/checkstyle/regression/module/ModuleInfoCollectorTest.java
- src/test/java/com/github/checkstyle/regression/module/ModuleUtilsTest.java
#45 
Including refactor of `GitChange` since there starts to be `equals` use in the UTs.
> Issue #45: Fix diff problems when parsing a branch behind master

- src/test/java/com/github/checkstyle/regression/git/DiffParserTest.java
- src/test/java/com/github/checkstyle/regression/internal/GitUtils.java
#18
IMO, PR branch behind master is not necessary. If the PR is not able to merge (has conflict), then we have no need to run the regression-tool at all. If the PR is able to merge, then we could do `git rebase master` first to let the PR branch ahead of master.
> Issue #18: Refine DiffParserTest

- README.md
> Issue #59: Create a documentation

- config/suppressions.xml
- pom.xml
- src/main/resources/com/github/checkstyle/regression/extract/ExtractInfoGeneratorTest.java
- src/main/resources/com/github/checkstyle/regression/extract/JsonUtil.java
> Issue #62: fixed checkstyle violations in injectable resources

- .ci/travis/checkstyle_regression_no_exception.sh
- .travis.yml
https://github.com/checkstyle/regression-tool/issues/15
Continuation of https://github.com/checkstyle/regression-tool/pull/61 .
> Issue #15: NoException Checkstyle Project Regression

- README.md
- src/main/java/com/github/checkstyle/regression/Main.java
#66 
the order of option changed.
localGitRepo => checkstyleLocalRepo
stopAfterGenerateConfig => stopAfterConfigGeneration
> Issue #66: Update documentation along with code changes

- README.md
- config/import-control.xml
- src/main/java/com/github/checkstyle/regression/configuration/ConfigGenerator.java
- src/main/java/com/github/checkstyle/regression/extract/CheckstyleInjector.java
#67 
Maybe we need to add a test of running outside source directory in Travis after #15 is done.
> Issue #67: Users should be able to run the tool in any directory

- pom.xml
- src/test/java/com/github/checkstyle/regression/module/ModuleUtilsTest.java
> Issue #80: added tests for ModuleUtils

- config/import-control.xml
> minor: added forbidden classes because of code coverage

- pom.xml
Issue #41
I couldn't upgrade Checkstyle as it was causing some issue with the tests. I need to examine it more.
> Issue #41: upgraded maven versions

- config/checkstyle_non_main_files_suppressions.xml
- pom.xml
> Issue #41: added non-main files checkstyle

- config/pmd-main.xml
- config/pmd-test.xml
- config/pmd.xml
- pom.xml
- src/test/java/com/github/checkstyle/regression/internal/FileUtils.java
- src/test/java/com/github/checkstyle/regression/internal/GitUtils.java
>  Issue #41: updated pmd validation 

- pom.xml
https://app.snyk.io/org/checkstyle/project/d9db8d9f-dbeb-47ed-a3dc-255478ba6bdf/#issue-SNYK-JAVA-COMPUPPYCRAWLTOOLS-543266
> config: bump checkstyle to avoid security vulnerability warning
